# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.12.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.12.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/kanberyuuta/dev/trifle_compiler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/kanberyuuta/dev/trifle_compiler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.12.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.12.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kanberyuuta/dev/trifle_compiler/CMakeFiles /Users/kanberyuuta/dev/trifle_compiler/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kanberyuuta/dev/trifle_compiler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tvm

# Build rule for target.
tvm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tvm
.PHONY : tvm

# fast build rule for target.
tvm/fast:
	$(MAKE) -f CMakeFiles/tvm.dir/build.make CMakeFiles/tvm.dir/build
.PHONY : tvm/fast

#=============================================================================
# Target rules for targets named trifle

# Build rule for target.
trifle: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 trifle
.PHONY : trifle

# fast build rule for target.
trifle/fast:
	$(MAKE) -f CMakeFiles/trifle.dir/build.make CMakeFiles/trifle.dir/build
.PHONY : trifle/fast

compile.o: compile.cpp.o

.PHONY : compile.o

# target to build an object file
compile.cpp.o:
	$(MAKE) -f CMakeFiles/trifle.dir/build.make CMakeFiles/trifle.dir/compile.cpp.o
.PHONY : compile.cpp.o

compile.i: compile.cpp.i

.PHONY : compile.i

# target to preprocess a source file
compile.cpp.i:
	$(MAKE) -f CMakeFiles/trifle.dir/build.make CMakeFiles/trifle.dir/compile.cpp.i
.PHONY : compile.cpp.i

compile.s: compile.cpp.s

.PHONY : compile.s

# target to generate assembly for a file
compile.cpp.s:
	$(MAKE) -f CMakeFiles/trifle.dir/build.make CMakeFiles/trifle.dir/compile.cpp.s
.PHONY : compile.cpp.s

gencode.o: gencode.cpp.o

.PHONY : gencode.o

# target to build an object file
gencode.cpp.o:
	$(MAKE) -f CMakeFiles/trifle.dir/build.make CMakeFiles/trifle.dir/gencode.cpp.o
.PHONY : gencode.cpp.o

gencode.i: gencode.cpp.i

.PHONY : gencode.i

# target to preprocess a source file
gencode.cpp.i:
	$(MAKE) -f CMakeFiles/trifle.dir/build.make CMakeFiles/trifle.dir/gencode.cpp.i
.PHONY : gencode.cpp.i

gencode.s: gencode.cpp.s

.PHONY : gencode.s

# target to generate assembly for a file
gencode.cpp.s:
	$(MAKE) -f CMakeFiles/trifle.dir/build.make CMakeFiles/trifle.dir/gencode.cpp.s
.PHONY : gencode.cpp.s

gettoken.o: gettoken.cpp.o

.PHONY : gettoken.o

# target to build an object file
gettoken.cpp.o:
	$(MAKE) -f CMakeFiles/trifle.dir/build.make CMakeFiles/trifle.dir/gettoken.cpp.o
.PHONY : gettoken.cpp.o

gettoken.i: gettoken.cpp.i

.PHONY : gettoken.i

# target to preprocess a source file
gettoken.cpp.i:
	$(MAKE) -f CMakeFiles/trifle.dir/build.make CMakeFiles/trifle.dir/gettoken.cpp.i
.PHONY : gettoken.cpp.i

gettoken.s: gettoken.cpp.s

.PHONY : gettoken.s

# target to generate assembly for a file
gettoken.cpp.s:
	$(MAKE) -f CMakeFiles/trifle.dir/build.make CMakeFiles/trifle.dir/gettoken.cpp.s
.PHONY : gettoken.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/trifle.dir/build.make CMakeFiles/trifle.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/trifle.dir/build.make CMakeFiles/trifle.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/trifle.dir/build.make CMakeFiles/trifle.dir/main.cpp.s
.PHONY : main.cpp.s

util.o: util.cpp.o

.PHONY : util.o

# target to build an object file
util.cpp.o:
	$(MAKE) -f CMakeFiles/tvm.dir/build.make CMakeFiles/tvm.dir/util.cpp.o
	$(MAKE) -f CMakeFiles/trifle.dir/build.make CMakeFiles/trifle.dir/util.cpp.o
.PHONY : util.cpp.o

util.i: util.cpp.i

.PHONY : util.i

# target to preprocess a source file
util.cpp.i:
	$(MAKE) -f CMakeFiles/tvm.dir/build.make CMakeFiles/tvm.dir/util.cpp.i
	$(MAKE) -f CMakeFiles/trifle.dir/build.make CMakeFiles/trifle.dir/util.cpp.i
.PHONY : util.cpp.i

util.s: util.cpp.s

.PHONY : util.s

# target to generate assembly for a file
util.cpp.s:
	$(MAKE) -f CMakeFiles/tvm.dir/build.make CMakeFiles/tvm.dir/util.cpp.s
	$(MAKE) -f CMakeFiles/trifle.dir/build.make CMakeFiles/trifle.dir/util.cpp.s
.PHONY : util.cpp.s

vmmain.o: vmmain.cpp.o

.PHONY : vmmain.o

# target to build an object file
vmmain.cpp.o:
	$(MAKE) -f CMakeFiles/tvm.dir/build.make CMakeFiles/tvm.dir/vmmain.cpp.o
.PHONY : vmmain.cpp.o

vmmain.i: vmmain.cpp.i

.PHONY : vmmain.i

# target to preprocess a source file
vmmain.cpp.i:
	$(MAKE) -f CMakeFiles/tvm.dir/build.make CMakeFiles/tvm.dir/vmmain.cpp.i
.PHONY : vmmain.cpp.i

vmmain.s: vmmain.cpp.s

.PHONY : vmmain.s

# target to generate assembly for a file
vmmain.cpp.s:
	$(MAKE) -f CMakeFiles/tvm.dir/build.make CMakeFiles/tvm.dir/vmmain.cpp.s
.PHONY : vmmain.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... tvm"
	@echo "... trifle"
	@echo "... compile.o"
	@echo "... compile.i"
	@echo "... compile.s"
	@echo "... gencode.o"
	@echo "... gencode.i"
	@echo "... gencode.s"
	@echo "... gettoken.o"
	@echo "... gettoken.i"
	@echo "... gettoken.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... util.o"
	@echo "... util.i"
	@echo "... util.s"
	@echo "... vmmain.o"
	@echo "... vmmain.i"
	@echo "... vmmain.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

